### ISSUE TITLE
Логгирование

### ISSUE THREAD

**Issue by Khorcus** [STRENCH0/UnitTests#1]
https://github.com/STRENCH0/UnitTests/blob/737f1cfb61ce2bcb64426c981ed5d6041d9e8127/src/main/java/ru/checka/test/log/PrintLogger.java#L9

Почему бы не заменить System.out.println()

**Comment by STRENCH0** [comment]
Заменить на что? Это всего лишь имплементация логгера для вывода в консоль. JUnit вроде как в консоль выводит тоже.

**Comment by Khorcus** [comment]
Ну, например использовать SLF4J.

**Comment by STRENCH0** [comment]
Добавил соответствующую имплементацию, хотя, как мне кажется, как часть фреймворка его использовать не очень удобно.
