### ISSUE TITLE
logger.logException глотает exception

### ISSUE THREAD

**Issue by vladimirkoba** [STRENCH0/UnitTests#2]
Когда случается ошибка, ты вызываешь следующий метод:
`
logger.logException(testClass, testMethod.getName(), e.getClass().getName());`
`
Здесь, вместо того, чтобы залогировать весь stacktrace из e, ты пишешь только имя ошибки. По нему разбираться в проблеме непросто.

Еще хуже, когда ты вместо одного Exception кидаешь вверх другой, не сохраняя никакой информации. Это прямо горе на отладке будет

**Comment by STRENCH0** [comment]
Исправил
